kind: Secret
apiVersion: v1
metadata:
  name: {{ include "test-helm.fullname" . }}
  labels:
    {{- include "test-helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  message: <path:{{ .Values.keyVaultName | required "Missing Key Vault name" }}#{{ .Values.secretName | required "Missing object name" }}>