apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: test-kustomize
    patch: |-
      - op: replace
        path: /data/value
        value: dXNlcgo=